[package]
name = "rdftk_iri"
version = "0.1.5"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
description = "This crate provides an implementation of the IRI and URI specifications."
documentation = "https://docs.rs/rdftk_core/"
repository = "https://github.com/johnstonskj/rust-rdftk.git"
license = "MIT"
readme = "README.md"
publish = true

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target for documentation.
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["builder", "path_iri", "uuid_iri"]
builder = []
path_iri = []
uuid_iri = ["uuid"]

[dependencies]
error-chain = "0.12.2"
lazy_static = "1.4.0"
regex = "1.3.7"
unique_id = "0.1.3"

uuid = { version = "0.8.1", optional = true }

[dev-dependencies]
proptest = "0.10.1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-test" ]
