[package]
name = "rdftk_io"
version = "0.1.4"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
description = "This crate provides traits for reading and writing Statements and Graphs as well as implementations of these for common representations."
documentation = "https://docs.rs/rdftk_core/"
repository = "https://github.com/johnstonskj/rust-rdftk.git"
license = "MIT"
readme = "README.md"
publish = true

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target for documentation.
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
error-chain = "0.12.2"
rdftk_core = { version = "0.1.6", path = "../rdftk_core" }
rdftk_iri = { version = "0.1.2", path = "../rdftk_iri" }

[dev-dependencies]
rdftk_memgraph = { version = "0.1.5", path = "../rdftk_memgraph" }
