[book]
title = "The RDFtk Book"
description = "RDFtk: An RDF Toolkit for Rust"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
src = "src"
language = "en"
multilingual = false

[build]
build-dir = "publish"
create-missing = true

[rust]
edition = "2018"

[output.html]
git-repository-url = "https://github.com/johnstonskj/rust-rdftk"
additional-css = ["src/additional.css"]
additional-js = ["src/turtle.js", "src/custom.js"]
mathjax-support = true
curly-quotes = true

[output.html.fold] 
enable = true
level = 2

[output.html.playpen]
line-numbers = true

[output.html.search]
use-boolean-and = true

